on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  deploy:
    env:
      AWS_S3_BUCKET: www.altostruct.com
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      SOURCE_DIR: "public"
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages and build the app
        run: |
          # Install node packages
          npm install --force
          # Build the app
          npm run build
      # Deploy to the S3 server
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          SOURCE_DIR: "out"
      - name: Invalidate cdn
        run: |
          # Declear bucket name
          export BUCKET_ORIGIN=$AWS_S3_BUCKET.s3.$AWS_REGION.amazonaws.com
          export DIST_ID=E2TAK3LG20RVA5
          echo "Found dist id $DIST_ID"
          echo $BUCKET_ORIGIN
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
